[build]
builder = "nixpacks"

[deploy]
startCommand = "cd plc-mentor && python app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8080"
FLASK_ENV = "production"